#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)/frontend" || exit 1

while read -r _ local_sha _ remote_sha
do
  [ -z "$local_sha" ] && continue
  [ "$remote_sha" = "0000000000000000000000000000000000000000" ] && continue

  pnpm exec commitlint -- --from "$remote_sha" --to "$local_sha"
done

